package poly.datn.main.model;
// Generated Sep 20, 2020 1:19:24 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmotionPost generated by hbm2java
 */
@Entity
@Table(name = "emotion_post", catalog = "graduate")
public class EmotionPost implements java.io.Serializable {

	private Long id;
	private Post postByUserId;
	private Post postByPostId;
	private long likes;
	private long dislike;

	public EmotionPost() {
	}

	public EmotionPost(Post postByUserId, Post postByPostId, long likes, long dislike) {
		this.postByUserId = postByUserId;
		this.postByPostId = postByPostId;
		this.likes = likes;
		this.dislike = dislike;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Post getPostByUserId() {
		return this.postByUserId;
	}

	public void setPostByUserId(Post postByUserId) {
		this.postByUserId = postByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_id", nullable = false)
	public Post getPostByPostId() {
		return this.postByPostId;
	}

	public void setPostByPostId(Post postByPostId) {
		this.postByPostId = postByPostId;
	}

	@Column(name = "likes", nullable = false)
	public long getLikes() {
		return this.likes;
	}

	public void setLikes(long likes) {
		this.likes = likes;
	}

	@Column(name = "dislike", nullable = false)
	public long getDislike() {
		return this.dislike;
	}

	public void setDislike(long dislike) {
		this.dislike = dislike;
	}

}
