package poly.datn.main.model;
// Generated Sep 20, 2020 1:19:24 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmotionAnswer generated by hbm2java
 */
@Entity
@Table(name = "emotion_answer", catalog = "graduate")
public class EmotionAnswer implements java.io.Serializable {

	private Long id;
	private Answer answerByAnswerId;
	private Answer answerByUserId;
	private Answer answerByPostId;
	private long likes;
	private long dislike;

	public EmotionAnswer() {
	}

	public EmotionAnswer(Answer answerByAnswerId, Answer answerByUserId, Answer answerByPostId, long likes,
			long dislike) {
		this.answerByAnswerId = answerByAnswerId;
		this.answerByUserId = answerByUserId;
		this.answerByPostId = answerByPostId;
		this.likes = likes;
		this.dislike = dislike;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "answer_id", nullable = false)
	public Answer getAnswerByAnswerId() {
		return this.answerByAnswerId;
	}

	public void setAnswerByAnswerId(Answer answerByAnswerId) {
		this.answerByAnswerId = answerByAnswerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Answer getAnswerByUserId() {
		return this.answerByUserId;
	}

	public void setAnswerByUserId(Answer answerByUserId) {
		this.answerByUserId = answerByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_id", nullable = false)
	public Answer getAnswerByPostId() {
		return this.answerByPostId;
	}

	public void setAnswerByPostId(Answer answerByPostId) {
		this.answerByPostId = answerByPostId;
	}

	@Column(name = "likes", nullable = false)
	public long getLikes() {
		return this.likes;
	}

	public void setLikes(long likes) {
		this.likes = likes;
	}

	@Column(name = "dislike", nullable = false)
	public long getDislike() {
		return this.dislike;
	}

	public void setDislike(long dislike) {
		this.dislike = dislike;
	}

}
