package poly.datn.main.model;
// Generated Sep 20, 2020 1:19:24 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job", catalog = "graduate")
public class Job implements java.io.Serializable {

	private Long id;
	private String name;
	private String description;
	private Date duedate;
	private String nameCompany;
	private double grossSalary;
	private Date createAt;
	private Date updateAt;
	private String tagId;
	private String cityId;

	public Job() {
	}

	public Job(String name, String description, Date duedate, double grossSalary, Date createAt, Date updateAt,
			String tagId, String cityId) {
		this.name = name;
		this.description = description;
		this.duedate = duedate;
		this.grossSalary = grossSalary;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.tagId = tagId;
		this.cityId = cityId;
	}

	public Job(String name, String description, Date duedate, String nameCompany, double grossSalary, Date createAt,
			Date updateAt, String tagId, String cityId) {
		this.name = name;
		this.description = description;
		this.duedate = duedate;
		this.nameCompany = nameCompany;
		this.grossSalary = grossSalary;
		this.createAt = createAt;
		this.updateAt = updateAt;
		this.tagId = tagId;
		this.cityId = cityId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "duedate", nullable = false, length = 19)
	public Date getDuedate() {
		return this.duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	@Column(name = "name_company")
	public String getNameCompany() {
		return this.nameCompany;
	}

	public void setNameCompany(String nameCompany) {
		this.nameCompany = nameCompany;
	}

	@Column(name = "gross_salary", nullable = false, precision = 15)
	public double getGrossSalary() {
		return this.grossSalary;
	}

	public void setGrossSalary(double grossSalary) {
		this.grossSalary = grossSalary;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_at", nullable = false, length = 19)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", nullable = false, length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@Column(name = "tag_id", nullable = false, length = 500)
	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	@Column(name = "city_id", nullable = false, length = 500)
	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

}
