package poly.datn.main.model;
// Generated Sep 20, 2020 1:19:24 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Point generated by hbm2java
 */
@Entity
@Table(name = "point", catalog = "graduate")
public class Point implements java.io.Serializable {

	private Long pointId;
	private User user;
	private long point;

	public Point() {
	}

	public Point(User user, long point) {
		this.user = user;
		this.point = point;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "point_id", unique = true, nullable = false)
	public Long getPointId() {
		return this.pointId;
	}

	public void setPointId(Long pointId) {
		this.pointId = pointId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "point", nullable = false)
	public long getPoint() {
		return this.point;
	}

	public void setPoint(long point) {
		this.point = point;
	}

}
